# Generated by Django 2.2.12 on 2020-07-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symphonius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(),
        ),
    ]
