# Generated by Django 2.2.12 on 2020-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symphonius', '0002_auto_20200708_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/video'),
        ),
    ]
